name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    steps:
      - uses: actions/checkout@master
      - name: Build elixir files
        run: |
          mix deps.get --only prod
          MIX_ENV=prod mix compile
          npm run deploy --prefix ./assets
          mix phx.digest
          MIX_ENV=prod mix release
      - name: Copy files to DO
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "_build/prod/**"
          target: "~/Apps/awards_predictor"
          